name: Selenium Grid Tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to test'
        required: false
        default: 'main'
      purge:
        description: 'Use the purge-local-repo profile to reset ~/.m2 before build'
        required: false
        default: 'false'
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  grid-tests:
    name: Test on ${{ matrix.os }} - ${{ matrix.browser }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            browser: chrome
          - os: ubuntu-latest
            browser: firefox
          - os: ubuntu-latest
            browser: edge
          - os: windows-latest
            browser: chrome
          - os: windows-latest
            browser: firefox
          - os: windows-latest
            browser: edge
          - os: macos-latest
            browser: chrome
          - os: macos-latest
            browser: firefox

    runs-on: ${{ matrix.os }}
    # Define Hub and Node containers as services
    services:
      selenium-hub:
        image: selenium/hub:4.33.0
        ports:
          - 4444:4444
      node:
        image: selenium/node-${{ matrix.browser }}:4.33.0
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with purge-local-repo
        if: ${{ github.event.inputs.purge == 'true' }}
        run: mvn clean install -Ppurge-local-repo -DresetCache

      - name: Build normally
        if: ${{ github.event.inputs.purge != 'true' }}
        run: mvn clean install

      - name: Run tests on ${{ matrix.browser }}
        run: mvn clean test -Dselenium.hub=http://localhost:4444 \
          -Dbrowser=${{ matrix.browser }} -DrunMode=grid

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-${{ matrix.browser }}
          path: target/allure-results

  merge-and-deploy:
    runs-on: ubuntu-latest
    needs: grid-tests
    if: always()
    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download All Allure Results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          merge-multiple: true
          path: target/allure-results

      - name: Install Allure CLI
        run: |
          sudo apt-add-repository ppa:qameta/allure -y
          sudo apt-get update
          sudo apt-get install -y allure

      - name: Generate merged Allure report
        run: |
          allure generate target/allure-results \
            --clean \
            -o target/allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/allure-report
